version: "2"

networks:
    hadoop_network:
        driver: bridge
    
services:
    nifi:
        image: erreesse/nifi
        container_name: nifi
        hostname: nifi
        networks:
            - hadoop_network
        ports:
            - "5555:5555"
        stdin_open: true
        tty: true

    master:
        build:
            context: ../docker-images/hdfs-yarn-spark
        image: erreesse/my-hds-yarn-spark
        container_name: master
        hostname: master
        networks:
            - hadoop_network
        ports:
            - "9870:9870"
            - "8088:8088"
            - "54310:54310"
        stdin_open: true
        tty: true

    slave1:
        image: erreesse/my-hds-yarn-spark
        container_name: slave1
        hostname: slave1
        networks:
            - hadoop_network
        ports:
            - "9864:9864"
        depends_on:
            - master
        stdin_open: true
        tty: true

  
    slave2:
        image: erreesse/my-hds-yarn-spark
        container_name: slave2
        hostname: slave2
        networks:
            - hadoop_network
        ports:
            - "9863:9864"
        depends_on:
            - master
        stdin_open: true
        tty: true


    slave3:
        image: erreesse/my-hds-yarn-spark
        container_name: slave3
        hostname: slave3
        networks:
            - hadoop_network
        ports:
            - "9862:9864"
        depends_on:
            - master
        stdin_open: true
        tty: true

        
    citylocationhelper:
        build:
            context: ../docker-images/citylocationhelper-python
        image: erreesse/citylocationhelper
        container_name: citylocationhelper
        hostname: citylocationhelper
        networks:
            - hadoop_network
        ports:
            - "8888:8888"
        environment:
            - TZ_HOST=0.0.0.0
            - TZ_PORT=8888
        stdin_open: true
        tty: true