version: "2"

networks:
    hadoop_network:
        driver: bridge
    
services:
    nifi:
        image: erreesse/nifi
        container_name: nifi
        hostname: nifi
        networks:
            - hadoop_network
        ports:
            - "5555:5555"
            - "43210:43210"
        volumes: 
            - ./nifi_conf:/usr/local/nifi/conf/flow
            - ./nifi_extensions:/usr/local/nifi/extensions
        stdin_open: true
        tty: true

    master:
        build:
            context: ../docker-images/hdfs-yarn-spark
        image: erreesse/my-hds-yarn-spark
        container_name: master
        hostname: master
        networks:
            - hadoop_network
        ports:
            - "9870:9870"
            - "8088:8088"
        volumes: 
            - ./spark_jar:/sabd/jar
        stdin_open: true
        tty: true
        environment: 
            - ISMASTER=1

    slave1:
        image: erreesse/my-hds-yarn-spark
        container_name: slave1
        hostname: slave1
        networks:
            - hadoop_network
        ports:
            - "9864:9864"
        depends_on:
            - master
        stdin_open: true
        tty: true
        environment: 
            - ISMASTER=0

  
    slave2:
        image: erreesse/my-hds-yarn-spark
        container_name: slave2
        hostname: slave2
        networks:
            - hadoop_network
        ports:
            - "9863:9864"
        depends_on:
            - master
        stdin_open: true
        tty: true
        environment: 
            - ISMASTER=0


    slave3:
        image: erreesse/my-hds-yarn-spark
        container_name: slave3
        hostname: slave3
        networks:
            - hadoop_network
        ports:
            - "9862:9864"
        depends_on:
            - master
        stdin_open: true
        tty: true
        environment: 
            - ISMASTER=0

        
    citylocationhelper:
        build:
            context: ../docker-images/citylocationhelper-python
        image: erreesse/citylocationhelper
        container_name: citylocationhelper
        hostname: citylocationhelper
        networks:
            - hadoop_network
        ports:
            - "8888:8888"
        environment:
            - TZ_HOST=0.0.0.0
            - TZ_PORT=8888
        stdin_open: true
        tty: true
        restart: on-failure

    hbase:
        image: erreesse/hbase
        container_name: hbase
        hostname: hbase
        networks:
            - hadoop_network
        ports:
            - "16010:16010"
        depends_on:
            - master
        stdin_open: true
        tty: true
        entrypoint: /entrypoint.sh

#   https://hub.docker.com/r/bitnami/kafka
#    zookeeper:
#        image: 'bitnami/zookeeper:latest'
#        ports:
#            - '2181:2181'
#        environment:
#            - ALLOW_ANONYMOUS_LOGIN=yes
#  
#    kafka:
#        image: 'bitnami/kafka:latest'
#        ports:
#        - '9092:9092'
#        environment:
#        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#        - ALLOW_PLAINTEXT_LISTENER=yes